# Generated by Django 5.1.6 on 2025-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('IT_MANAGER', 'IT Manager'), ('SECURITY_ANALYST', 'Security Analyst'), ('EMPLOYEE', 'Employee'), ('IT_SPECIALIST', 'IT Specialist')], max_length=20)),
            ],
        ),
    ]
