# Generated by Django 5.1.6 on 2025-04-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
    ]
