# Generated by Django 5.1.6 on 2025-04-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_attack_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact_type',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('feedback', 'Feedback'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion')], default='inquiry', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='requested_attacks',
            field=models.TextField(blank=True, help_text='Attack types requested to be added', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
