# Generated by Django 5.1.6 on 2025-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_question_explanation_scenario_ai_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ransomwarescenario',
            name='ransom_amount_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ransomwarescenario',
            name='ransom_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
