# Generated by Django 5.1.6 on 2025-04-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_ransomwarescenario_ransom_amount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
