# Generated by Django 5.1.6 on 2025-04-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_attack_types'),
        ('training', '0004_scenario_json_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredScenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('json_data', models.JSONField()),
                ('attack_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.attacktype')),
            ],
        ),
    ]
