# Generated by Django 5.1.6 on 2025-05-01 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_remove_mitmscenario_scenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDoSScenario',
            fields=[
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='training.scenario')),
                ('type_of_ddos', models.CharField(max_length=100)),
                ('attack_vector', models.CharField(max_length=200)),
                ('targeted_service', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MitMScenario',
            fields=[
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='training.scenario')),
                ('type_vector', models.CharField(max_length=200)),
                ('data_intercepted', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RansomwareScenario',
            fields=[
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='training.scenario')),
                ('initial_infection_vector', models.CharField(max_length=200)),
                ('ransom_amount_text', models.CharField(default='', max_length=200)),
                ('ransom_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
