# Generated by Django 5.1.6 on 2025-05-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_ddosscenario_mitmscenario_ransomwarescenario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitmscenario',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='ransomwarescenario',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='ai_response',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='raw_response',
        ),
        migrations.DeleteModel(
            name='DDoSScenario',
        ),
        migrations.DeleteModel(
            name='MitMScenario',
        ),
        migrations.DeleteModel(
            name='RansomwareScenario',
        ),
    ]
